Lesson 6
hookbil/rails_learning pull request #6
Opened 2018-11-17 21:44 UTC by hookbil

2018-11-18 00:13 UTC, psylone requested changes

2018-11-18 00:13 UTC, psylone commented on test-guru/app/models/test.rb
> +    joins(:category).where(categories: {title: category_title}).order(:title).pluck(:title)
Скоуп метод по соглашению должен возвращать объект класса `ActiveRecord::Relation`, чтобы его можно было вызывать по цепочке с другими скоупами, методами ассоциаций или методами ActiveRecord.

Также сортировку стоит вынести за пределы скоупа.

2018-11-18 00:13 UTC, psylone commented on test-guru/app/models/test.rb
>        .where(categories: { title: category_title }).order(:title).pluck(:title)
Используй скоуп метод.

2018-11-18 00:13 UTC, psylone commented on test-guru/app/models/user.rb
> +  scope :test_by_level, -> (user, level)  {
Не злоупотребляй скоупами. В данном случае достаточно инстанс метода:

```ruby
def tests_by_level(level)
  tests.where(level: level)
end
```

2018-11-18 00:13 UTC, psylone commented on test-guru/app/models/test.rb
> +  validates :title, presence: true, uniqueness: { scope: :level}
Необходимо добавить составной уникальный индекс в базе данных.

2018-11-19 09:49 UTC, BubuntuClu commented on test-guru/app/models/test.rb
> +    titles_by_category(category_title).pluck(:title)
сортировку потерял

2018-11-19 09:49 UTC, BubuntuClu commented on test-guru/db/migrate/20181117213158_change_default_level_of_test.rb
> +    change_column_default :tests, :level, from: 0, to: 1
а это зачем менять? у тебя есть скоуп с легкими тестами, там начинается с 0

2018-11-19 18:09 UTC, psylone approved these changes

2018-11-20 14:24 UTC, merged